name: Ka0s JSON Lint

on:
  workflow_dispatch: # Workflow manualmente
    inputs:
      kaos-origin:
        description: 'Dispatcher Workflow Run ID'
        default: ""
        required: true
      kaos-files:
        description: 'Files Involved'
        default: ""
        required: true
      kaos-issue-id:
        description: 'Issue ID'
        default: "Kaos Issue ID"
        required: true
  
permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write

env:
  KAOS_MODULE: "[Ka0S] JSONLINT"
  GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
  PATH_RESUME: "core/results/"
  FILE_ERROR: ""
  USER_NAME: ${{ secrets.KAOS_USER_NAME }}
  USER_EMAIL: ${{ secrets.KAOS_USER_EMAIL }}

jobs:
  json-lint-process:
    runs-on: 
      group: kaos-jsonlint

    steps:
      - id: repo # Checkout the repository to get the information of the commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_TOKEN }}
    
      - id: install-node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - id: install-jsonlint
        run: |
          npm install -g jsonlint
        continue-on-error: true
  
      - id: check-json
        run: |
            # Invocamos la primera comprobación de base, sino se supera el proceso no continua
            # Extraemos el nombre del fichero
            file_name=$(basename "${{ github.event.inputs.kaos-files }}")
            # Generamos el fichero de resultados vacio
            touch ${{ env.PATH_RESUME }}jsonlint-results-${{ github.run_id }}.txt
            # Realizamos el check del documento json 
            jsonlint ${{ github.event.inputs.kaos-files }} -c -p > ${{ env.PATH_RESUME }}jsonlint-results-${{ github.run_id }}.txt 2>&1 || true
            # Check if exist errors in file
            if [ ! -s ${{ env.PATH_RESUME }}jsonlint-results-${{ github.run_id }}.txt ]; then
              echo "File ${{ env.PATH_RESUME }}jsonlint-results-${{ github.run_id }}.txt is empty and is content correct"
              KAOS_ISSUE_BODY="The ${{ env.KAOS_MODULE }} process (${{ github.event.inputs.kaos-origin }}) launch the check (${{ github.run_id }}) over file (${{ github.event.inputs.kaos-files }}) and its result has been SUCCESS. Please review all files implicated in pull request and approve to merge"
              gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title="" -f kaos-issue-body="$KAOS_ISSUE_BODY" -f kaos-issue-actions=comment -f kaos-issue-tag="" -f kaos-issue-id=${{ github.event.inputs.kaos-issue-id }}
            else
              echo "File ${{ env.PATH_RESUME }}jsonlint-results-${{ github.run_id }}.txt is not empty and is content not correct and write commit info"
              echo "FILE_ERROR=${{ env.PATH_RESUME }}jsonlint-results-${{ github.run_id }}.txt" >> $GITHUB_ENV
              KAOS_ISSUE_BODY="The ${{ env.KAOS_MODULE }} process (${{ github.event.inputs.kaos-origin }}) launch the check (${{ github.run_id }}) over file (${{ github.event.inputs.kaos-files }}) and its result has been FAILED, please check ${{ env.PATH_RESUME }}jsonlint-results-${{ github.run_id }}.txt and solved it"
              gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title="" -f kaos-issue-body="$KAOS_ISSUE_BODY" -f kaos-issue-actions=comment -f kaos-issue-tag="" -f kaos-issue-id=${{ github.event.inputs.kaos-issue-id }} 
            fi

  handle_failure:
    runs-on: 
      group: kaos-jsonlint
    needs: [json-lint-process]
    if: ${{ failure() }}
    steps:
      - id: check-execution
        env:
          GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
        run: |
          echo "Error detected in ${{ env.KAOS_MODULE }}, creating issue..."
          KAOS_ISSUE_TITLE="${{ env.KAOS_MODULE }} Action Failed: ${{ github.workflow }}"
          KAOS_ISSUE_BODY=$(cat <<'EOF'
          An error occurred in the ${{ env.KAOS_MODULE }} Action workflow **${{ github.workflow }}**.
          **${{ env.KAOS_MODULE }}  Message:**
          El error ha sido en : ${{  github.run_id }}
          ejecute este comando en su consola y podrá consultar el fallo del trabajo
          gh run view ${{  github.run_id }} --log-failed
          y compruebe el fichero: ${{ env.FILE_ERROR}}
          \`\`\`
          **Please check the job logs for ${{ secrets.KAOS_ACTIONS_URL }}${{ github.run_id }}**
          \`\`\`
          **Workflow Name:** ${{ github.workflow }}
          **Job Name:** ${{ github.job }}
          **Run ID:** ${{ github.run_id }}
          **Run Number:** ${{ github.run_number }}
          **Repository:** ${{ github.repository }}
          **Branch:** ${{ github.ref }}
          **Commit:** ${{ github.sha }}
          Please investigate the issue.
          EOF
          )
          gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title="$KAOS_ISSUE_TITLE" -f kaos-issue-body="$KAOS_ISSUE_BODY" -f kaos-issue-actions=create -f kaos-issue-tag="bug"   
  